Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_4_FE, pull requests merged in 2024-05, with the labels that each got.

#56 Feat/signup fix
  src/app/login/captcha/page.tsx
  src/app/login/more/page.tsx
  src/app/login/verification/page.tsx
  src/app/moreinfo/med/page.tsx
  src/app/moreinfo/pre/page.tsx
  src/app/moreinfo/trans/page.tsx
  src/app/signup/moreidentity/page.tsx
Labels: feat, QA/Fix

#57 Feat/signup bug
  package-lock.json
  package.json
  public/assets/image/img-Vacgom-loading.svg
  src/app/_component/molecule/WorningToastWrap/index.tsx
  src/app/_component/molecule/WorningToastWrap/style.ts
  src/app/_component/temp/Loading/index.tsx
  src/app/_component/temp/Loading/style.ts
  src/app/_lib/postFindChallenge.ts
  src/app/_lib/postSMSCode.ts
  src/app/_lib/postSignup.ts
  src/app/_lib/postVacSignup.ts
  src/app/_lib/postchallenge.ts
  src/app/login/captcha/page.tsx
  src/app/login/verification/page.tsx
  src/app/moreinfo/dis/page.tsx
  src/app/moreinfo/id/page.tsx
  src/app/page.tsx
  src/app/signup/captcha/page.tsx
  src/app/signup/info/page.tsx
  src/app/signup/moreidentity/page.tsx
  src/app/signup/verification/page.tsx
  src/styles/images.ts
  src/types/globalType.ts
Labels: feat

#58 ♻️ Refactor : 병원 조회 기능 QA 피드백 반영 및 코드 리팩토링 및 API 우회 연결
  public/assets/ico/ico-map-home.svg
  src/app/_component/atom/CurrectToast/index.tsx
  src/app/_component/atom/MapModal/index.tsx
  src/app/_component/atom/MapModal/styles.ts
  src/app/_component/atom/ReloadButton/index.tsx
  src/app/_component/atom/ReloadButton/style.ts
  src/app/_component/organism/mainMap/index.tsx
  src/app/_component/temp/hpvhospitalmap/index.tsx
  src/app/_component/temp/hpvsupportIntro/index.tsx
  src/app/_component/temp/influhospitalmap/index.tsx
  src/app/_component/temp/influsupportIntro/index.tsx
  src/pages/map/index.tsx
  src/utils/hpv-api.js
  src/utils/hpv-api.json
  src/utils/influ-api.js
  src/utils/influ-api.json
Labels: Refactor

#61 Feat/signup bug
  src/app/_component/atom/BottomButton/index.tsx
  src/app/_component/atom/InputForm/index.tsx
  src/app/_component/temp/SkeletonScreen/index.tsx
  src/app/_component/temp/SkeletonScreen/style.ts
  src/app/_lib/postLogin.ts
  src/app/login/find/page.tsx
  src/app/login/helper/page.tsx
  src/app/moreinfo/dis/page.tsx
  src/app/signup/info/page.tsx
  src/app/signup/more/page.tsx
  src/app/signup/page.tsx
  src/app/vachistory/certificate/[id]/page.tsx
  src/routes/path.ts
Labels: QA/Fix

#71 (QA after) Feat : 여러가지 수정...
  next.config.mjs
  package-lock.json
  package.json
  public/assets/image/img-syringe.svg
  public/assets/image/index.ts
  src/app/_component/atom/BottomButton/index.tsx
  src/app/_component/atom/InputForm/index.tsx
  src/app/_component/atom/InputForm/styles.ts
  src/app/_component/atom/VaccineDetail/index.tsx
  src/app/_component/atom/VaccineDetail/styles.ts
  src/app/_component/atom/VaccineStatus/index.tsx
  src/app/_component/atom/WarningToast/styles.ts
  src/app/_component/molecule/NonePage/index.tsx
  src/app/_component/molecule/NonePage/style.ts
  src/app/_component/temp/JoinTemplate/index.tsx
  src/app/_lib/getInoculationDetail.ts
  src/app/_lib/getInoculationSimple.ts
  src/app/login/helper/page.tsx
  src/app/login/more/page.tsx
  src/app/login/verification/page.tsx
  src/app/signup/done/page.tsx
  src/app/signup/more/page.tsx
  src/app/signup/terms/page.tsx
  src/app/signup/terms/style.ts
  src/app/signup/verification/page.tsx
  src/app/vachistory/vaccine/[id]/page.tsx
  src/app/vachistory/vaccine/page.tsx
  src/app/vachistory/vaccine/style.ts
  src/pages/detaildis/[id].tsx
  src/styles/images.ts
Labels: bug
